facebook/urls.py
from django.conf.urls import url 
from . import views

app_name = 'facebook'

urlpatterns=[

	url(r'^$', views.index, name='index'),
	url(r'^logout$', views.logout, name='logout'),
	url(r'^register$', views.signUp, name='signUp'),
	url(r'^profile$', views.profile, name='profile'),
	url(r'^profile/uploaded$', views.validate_upload, name='validate_upload'),
	url(r'^profile/edited$', views.edit_info, name='edit_info'),
	url(r'^profile/posted$', views.make_post, name='make_post'),
	url(r'^profile/liked$', views.like_post, name='like_post'),
	url(r'^profile/deleted$', views.delete_post, name='delete_post'),
	url(r'^view profile$', views.search_user, name='search_user'),
	url(r'^view profile/liked$', views.like_post_other_profile, name='like_post_other_profile'),
	url(r'^view profile/MsgSent$', views.send_msg_other_profile, name='send_msg_other_profile'),
	url(r'^ajax/messages/$', views.messager, name='messager'),
		
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^', include('facebook.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

facebook/models.py
from django.db import models
import datetime

class User(models.Model):

	user_name = models.CharField(max_length=200)
	user_password = models.CharField(max_length=200)
	user_email = models.CharField(max_length=200)

	def generate_chat_thread(self):
		counter = 0
		if self.contact_set.all():
			for contact in self.contact_set.all():
				if contact.conversation_set.all():
					print()
					print(contact.conversation_set.all().count())
					counter += contact.conversation_set.all().count()
		return counter

	def generate_contact_thread(self):
		return self.contact_set.all()

	def __str__(self):
		return self.user_name
		
	def __str__(self):
		return self.user_password
		
	def __str__(self):
		return self.user_email
	

class User_Options(models.Model):

	user_reference = models.ForeignKey(User, on_delete=models.CASCADE)
	about_bio = models.CharField(max_length=2000)
	about_location = models.CharField(max_length=100)

	def __str__(self):
		return self.about_bio
		
	def __str__(self):
		return self.about_location
		
	def __str__(self):
		return self.about_post

		
		
class User_Posts(models.Model):

	user_reference = models.ForeignKey(User, on_delete=models.CASCADE)
	post_made = models.CharField(max_length=10000)
	pub_date = models.DateTimeField('Date Published')
	likes = models.IntegerField(default=0)
	
	def __str__(self):
		return self.post_made
		
		
class User_Photo(models.Model):

	user_reference = models.ForeignKey(User, on_delete=models.CASCADE)
	profile_picture_link = models.CharField(max_length=10000)
	
	def __str__(self):
		return self.profile_picture_link


class Contact(models.Model):

	user_reference = models.ForeignKey(User, on_delete=models.CASCADE)
	contact_id = models.IntegerField(default=0)
	contact_name = models.CharField(max_length=10000)
	contact_email = models.CharField(max_length=10000)
		
	def __str__(self):
		return self.contact_id

	def __str__(self):
		return self.contact_name
		
	def __str__(self):
		return self.contact_email


class Conversation(models.Model):
		
	contact_reference = models.ForeignKey(Contact, on_delete=models.CASCADE)
	contact_id = models.IntegerField(default=0)
	contact_name = models.CharField(max_length=10000)
	contact_email = models.CharField(max_length=10000)
	msg_content = models.CharField(default='', max_length=10000)
	sent_on = models.DateTimeField('Date Published', default=datetime.datetime.now)
	has_been_read = models.BooleanField(default=False, blank=True)
	
	def __str__(self):
		return self.contact_name
		
	def __str__(self):
		return self.msg_content

facebook/views.py
from django.shortcuts import render, get_object_or_404
from facebook.models import User, Contact, Conversation
import datetime
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.core.files.base import ContentFile
from django.http import HttpResponseRedirect, HttpRequest, JsonResponse
from django.urls import reverse


def create_welcome_message(new_user):
	master, master_status = User.objects.get_or_create(user_name="Larry Georges", user_email="host@test.com", user_password="12345")
	init_contact, contact_status = Contact.objects.get_or_create(user_reference=new_user, contact_id=master.id, contact_name=master.user_name, contact_email=master.user_email)
	init_chat, chat_status = Conversation.objects.get_or_create(contact_reference=init_contact, contact_id=init_contact.id, contact_email=init_contact.contact_email, contact_name=init_contact.contact_name, msg_content='Welcome to the FaceBook Clone <br />♦ Have a pleasant experience ☻ ♦')

def check_for_unread_messages(verified_user):
	if verified_user.contact_set.all():
		for contact in verified_user.contact_set.all():
			if contact.conversation_set.all():
				unread_status = contact.conversation_set.filter(has_been_read=False)
				if unread_status:
					return True, contact.id
	return False, ''

def check_logins_and_signups_status(request):
	statuses = {'signup_status': '', 'login_status': ''}
	if request.session.has_key('new_user'):
		#skip to profile
		#return HttpResponseRedirect(reverse('facebook:profile'))
		pass
	if request.session.has_key('sign_up_error'):
		statuses['signup_status'] = ' Account Already Existent. <br>Please Log in or Use a Different Email Address '
		del request.session['sign_up_error']
	if request.session.has_key('sign_up_existent'):
		statuses['signup_status'] = ' Account Already Existent. <br>Please Log in or Use a Different Email Address '
		del request.session['sign_up_existent']
	if request.session.has_key('login_invalid'):
		statuses['login_status'] = ' Invalid Details. Please Try Again '
		del request.session['login_invalid']
	if request.session.has_key('login_non_existent'):
		statuses['login_status'] = ' Details Non Existent. Please Create An Account '
		del request.session['login_non_existent']
	return statuses


def index(request):
	return render(request, 'facebook/index.html', context={'statuses': check_logins_and_signups_status(request)})

def logout(request):
	if request.session.has_key('new_user'):
		del request.session['new_user']
	return HttpResponseRedirect(reverse('facebook:index'))


def check_if_user_is_authed(request):
	##Logging in with cookies
	new_user = ''
	if request.session.has_key('new_user'):
		try:
			new_user = User.objects.get(id=request.session['new_user'])
		except KeyError:
			return HttpResponseRedirect(reverse('facebook:index'))
	return new_user

def log_profile_visited(request):
	##Logging in with cookies
	visit = ''
	if request.session.has_key('profile_visited'):
		try:
			visit = User.objects.get(id=request.session['profile_visited'])
		except KeyError:
			return HttpResponseRedirect(reverse('facebook:profile'))
	return visit

def check_if_user_is_logged_in(request):
	logged_in = check_if_user_is_authed(request)
	if logged_in:
		return HttpResponseRedirect(reverse('facebook:profile'))
	return HttpResponseRedirect(reverse('facebook:index'))


def signUp(request):
	
	new_user = check_if_user_is_authed(request)

	if request.method == 'POST':
		captured_user_name = request.POST.get('userName', None)
		captured_user_email = request.POST.get('userEmail', None)
		captured_user_password = request.POST.get('userPassword', None)
		
		try:
			fetching_user = User.objects.get(user_email=captured_user_email)
			request.session['sign_up_error'] = True
			return HttpResponseRedirect(reverse('facebook:index'))
			
		except User.MultipleObjectsReturned:
			request.session['sign_up_existent'] = True
			return HttpResponseRedirect(reverse('facebook:index'))
			
		except User.DoesNotExist:
			#saving to database
			new_user = User(user_name=captured_user_name, user_email=captured_user_email, user_password=captured_user_password)
			new_user.save()
			request.session['new_user'] = new_user.id
			return HttpResponseRedirect(reverse('facebook:signUp'))

	context={
		'new_user': new_user,
	}
	return render(request, 'facebook/signUp.html', context)
	
	
def profile(request):
	
	verified_user = check_if_user_is_authed(request)

	if request.method == 'POST':
		captured_user_email = request.POST.get('checkUserEmail', None)
		captured_user_password = request.POST.get('checkUserPassword', None)
		
		try:
			fetched_user = User.objects.get(user_email=captured_user_email)
			
			if fetched_user.user_email == captured_user_email and fetched_user.user_password == captured_user_password:
				create_welcome_message(fetched_user)
				return HttpResponseRedirect(reverse('facebook:profile'))		
				
			else:
				request.session['login_invalid'] = True
				return HttpResponseRedirect(reverse('facebook:index'))
				
		except User.DoesNotExist:
			request.session['login_non_existent'] = True
			return HttpResponseRedirect(reverse('facebook:index'))

	has_unread_messages, unread_contact_id = check_for_unread_messages(verified_user)

	context={
		'verified_user': verified_user,
		'all_users': User.objects.exclude(id=verified_user.id),
		'has_unread_messages': has_unread_messages,
		'unread_contact_id': unread_contact_id
	}
	return render(request, 'facebook/profile.html', context)
	
	
def messager(request):
	
	change_status = request.GET.get('change_status', None)
	change_item = request.GET.get('change_item', None)
	message_item = request.GET.get('message_item', None)

	if change_status == 'read':
		try:
			contact_from_msg = Contact.objects.get(id=str(change_item))
			filtered_tread = contact_from_msg.conversation_set.filter(has_been_read=False)
			if filtered_tread:
				for msg in filtered_tread:
					msg.has_been_read = True
					msg.save()
		except Exception as error:
			print(error)
		''' Real time update help on models needed here '''
		circle_user = check_if_user_is_authed(request)
		circle_user = circle_user.generate_chat_thread()
		''' End Real time update help needed '''
		data = {
			'is_taken': True,
			'marked_read': True,
			'change_item': change_item
		}
		return JsonResponse(data)

	if change_status == 'response':
		try:
			contact_from_msg = Contact.objects.get(id=str(change_item))
			Conversation.objects.create(contact_reference=contact_from_msg, contact_id=contact_from_msg.id, contact_email=contact_from_msg.contact_email, contact_name=contact_from_msg.contact_name, msg_content=message_item, has_been_read=True)
		except Exception as error:
			print(error)

		data = {
			'is_taken': True,
			'new_response': True,
			'change_item': change_item,
			'message_item': message_item
		}
		return JsonResponse(data)

	data = {
		'is_taken': False
	}
	return JsonResponse(data)


def edit_info(request):

	if request.method == 'POST':		
		verified_user = check_if_user_is_authed(request)
		captured_user_about = request.POST.get('textAreaAbout', None)
		captured_user_location = request.POST.get('inputLocation', None)
		
		#cleaning database
		verified_user.user_options_set.all().delete()
		#saving to database
		verified_user.user_options_set.create(about_bio=captured_user_about, about_location=captured_user_location)
			
	return HttpResponseRedirect(reverse('facebook:profile'))



def make_post(request):

	if request.method == 'POST':	
		verified_user = check_if_user_is_authed(request)
		captured_user_post = request.POST.get('textAreaPost', None)

		#saving to database
		verified_user.user_posts_set.create(post_made=captured_user_post, pub_date=datetime.datetime.now(), likes=0)
		
	return HttpResponseRedirect(reverse('facebook:profile'))	

	
def like_post(request):

	if request.method == 'POST':		
		verified_user = check_if_user_is_authed(request)
		captured_user_post_id = request.POST.get('checkPostID', None)
		
		#finding post in database
		selected_post = verified_user.user_posts_set.get(id=captured_user_post_id)
		selected_post.likes += 1
		selected_post.save()
		
	return HttpResponseRedirect(reverse('facebook:profile'))
	

def delete_post(request):

	if request.method == 'POST':	
		verified_user = check_if_user_is_authed(request)
		captured_user_post_id = request.POST.get('checkPostID', None)
		
		#finding post in database
		selected_post = verified_user.user_posts_set.get(id=captured_user_post_id)
		selected_post.delete()
		
	return HttpResponseRedirect(reverse('facebook:profile'))

	
def search_user(request):

	verified_user = check_if_user_is_authed(request)
	
	captured_user_profile = request.GET.get('profileSelected', None)
	
	#finding user in database
	selected_user_profile = ''
	if captured_user_profile:
		try:
			selected_user_profile = User.objects.filter(user_name=captured_user_profile).first()
			request.session['profile_visited'] = selected_user_profile.id 
		except Exception as error:
			print(error)
			return HttpResponseRedirect(reverse('facebook:profile'))
	else:
		selected_user_profile = log_profile_visited(request)
	
	#fetching in database
	all_users = User.objects.exclude(id=verified_user.id)

	context={
		'verified_user': verified_user,
		'selected_user_profile': selected_user_profile,
		'all_users': all_users,
	}
	return render(request, 'facebook/view_other_profile.html', context)
	
	
	
	
def like_post_other_profile(request):

	if request.method == 'POST':	
		verified_user = check_if_user_is_authed(request)
		captured_user_post_id = request.POST.get('checkPostID', None)
		
		#finding post in database
		selected_user_profile = log_profile_visited(request)
		
		#finding post in database
		selected_post = selected_user_profile.user_posts_set.get(id=captured_user_post_id)
		selected_post.likes += 1
		selected_post.save()
		
	return HttpResponseRedirect(reverse('facebook:search_user'))


def send_msg_other_profile(request):

	if request.method == 'POST':	

facebook/templates/facebook/signUp.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Registration | Facebook Clone</title>
	<link rel="shortcut icon" type="image/png" href="{% static 'facebook/images/favicon.png' %}"/>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
	<div class="container-fluid" style="text-align: center; margin-top: 2%;">
		<h2>
			<span>Face</span><span class="bg-primary" style="font-weight: bold; padding: 5px; border-radius: 15%;">Book</span> 
			Clone
		</h2>
		<br />
		<h3>Congratulations - Account Successfully Created</h3>
		<br />
	</div>

	<div class="container-fluid">
		<div class="panel panel-primary" style="margin: auto; max-width: 500px;">
			<div class="panel-heading" style="text-align: center; background-color: rgba(0, 0, 255, .9);">
				<h2>Details of <strong>{{ new_user.user_name.capitalize }}</strong></h2>
			</div>
			<div class="panel-body" style="text-align: center;">
				<p>Name: <strong>{{ new_user.user_name.capitalize }}</strong></p>
				<p>Email: <strong>{{ new_user.user_email }}</strong></p>
				<p>Password: <strong>{{ new_user.user_password }}</strong></p>
			</div>
			<div class="panel-footer panel-danger">
				<span class="glyphicon glyphicon-fire" style="color:rgba(0, 0, 255, .6);"></span>
			</div>
		</div>

		<div style="width: 100%; text-align: center;">
			<form action="{% url 'facebook:profile' %}" method="POST"> 
				{% csrf_token %}
				<input style="display: none;" type="hidden" name="checkUserEmail" value="{{ new_user.user_email }}" /><br />
				<input style="display: none;" type="hidden" name="checkUserPassword" value="{{ new_user.user_password }}" /><br /><br />
				<button class="btn btn-primary" type="submit">Continue to Profile</button>
			</form>
		</div>
	</div>
</body>

</html>

facebook/templates/facebook/view_other_profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Friends Profile | Facebook Clone</title>
	<link rel="shortcut icon" type="image/png" href="{% static 'facebook/images/favicon.png' %}"/>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<style>
@media screen and (max-width: 600px){
	.FaceClone-header{display: block;}
	.top-navigation-items{margin-right: 10% !important;}
	.clone-profile-container{margin: 5% 0.5% 0 0.5% !important;}
	.clone-profile-picture-container{float: none !important; margin-bottom: 50px;}
	.clone-profile-picture{width: 100% !important;}
	.clone-about-container{width: 100% !important;}
}
</style>
<body>

<div class="container-fluid" style="text-align: center; margin-top: 0%;">
		<h2 class="FaceClone-header" style="float: left; margin-left: 1%;">
			<span>Face</span><span class="bg-primary" style="font-weight: bold; padding: 5px; border-radius: 15%;">Book</span> 
			Clone
		</h2>
		
		
		<h2 class="top-navigation-items" style="float: right; margin-left: 2%; margin-right: 1%;"><a href="{% url 'facebook:logout' %}" title="Logout"><span class="glyphicon glyphicon-off"></span></a></h2>
		
		<h2 class="top-navigation-items" style="float: right; margin-left: 2%; margin-right: 1%;"><a data-toggle="modal" data-target="#mySearch" href="#" title="View other users..."><span class="glyphicon glyphicon-search"></span></a></h2>
		<!-- Pop up -->
		<!-- Modal -->
		<div class="modal fade" id="mySearch" role="dialog">
			<div class="modal-dialog">
				<!-- Modal content-->
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">&times;</button>
						<h4 class="modal-title">View other profiles...</h4>
					</div>
					<form action="{% url 'facebook:search_user' %}" method="GET"> 
					<div class="modal-body">	
						<div class="form-group">								
							<label for="sel1" style="float: left;">Select user profile to see:</label>
							<select class="form-control" id="sel1" name="profileSelected">
								{% for user in all_users %}
								<option>{{ user.user_name }}</option>
								{% endfor %}
							</select>
						</div>
					</div>
					<div class="modal-footer">
						<button type="submit" class="btn btn-primary">Search</button>
						<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					</div>
					</form>
				</div>
			</div>
		</div>
		<!-- End Pop up-->
		<h2 class="top-navigation-items" style="float: right; margin-left: 2%; margin-right: 1%;"><a data-toggle="modal" data-target="#myMsg" href="#" title="Send Message To {{ selected_user_profile.user_name.capitalize }}"><span class="glyphicon glyphicon-envelope"></span></a></h2>
		<!-- Pop up -->
		<!-- Modal -->
		<div class="modal fade" id="myMsg" role="dialog">
			<div class="modal-dialog">
				<!-- Modal content-->
				<div class="modal-content">
					<div class="modal-header bg-primary">
						<button type="button" class="close" data-dismiss="modal">&times;</button>
						<h4 class="modal-title">Messages</h4>
					</div>
					<form action="{% url 'facebook:send_msg_other_profile' %}" method="POST"> 
						{% csrf_token %} 
						<div class="modal-body bg-default">	
							<div style="width: 100%; padding: 30px; margin: 10px 0; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);" class="form-group">
								<label style="float: left;" for="Msgcomment">Send Message To <span style="color: brown;">{{ selected_user_profile.user_name.capitalize }}</span>:</label>
								<textarea class="form-control" rows="5" id="Msgcomment" name="textAreaSendMsg" required></textarea>
								<br />
								<input style="display: none;" type="text" name="checkUserID" value="{{ verified_user.id }}" />
								<input style="display: none;" type="text" name="checkUserIDmsgReceiver" value="{{ selected_user_profile.id }}" />
								<button type="submit" class="btn btn-danger">Send</button>
								<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
							</div>						
						</div>
					</form>
				</div>
			</div>
		</div>
		<!-- End Pop up-->
		<h2 class="top-navigation-items" style="float: right; margin-left: 2%; margin-right: 1%;"><a href="{% url 'facebook:profile' %}" title="Back To Your Profile"><span class="glyphicon glyphicon-user"></span></a></h2>	
	<br /><br /><br />
</div>

<div class="container-fluid">
	<div class="panel panel-warning clone-profile-container" style="margin: 0 1%;">
		<div class="panel-heading">
			<h2 style="color: brown;">{{ selected_user_profile.user_name.capitalize }}'s Profile</h2>
		</div>
		<div class="panel-body" style="text-align: left;">
			<div class="clone-profile-picture-container" style="float: left;">
				<img title="View Profile Picture" data-toggle="modal" data-target="#myImage" class="img-rounded clone-profile-picture" style="cursor:pointer; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19); width:300px; height:284px;" 
				{% if selected_user_profile.user_photo_set.all %}
				{% for data in selected_user_profile.user_photo_set.all %}
					src="{{ data.profile_picture_link }}"
				{% endfor %}
				{%  else %}
				src="http://vignette1.wikia.nocookie.net/charmscrp/images/a/ac/Generic_Avatar.png/revision/latest?cb=20140819033443"
				{% endif %}
				/>
				<!-- Pop up -->
				<!-- Modal -->
				<div class="modal fade" id="myImage" role="dialog">
					<div class="modal-dialog">
						<!-- Modal content-->
						<div class="modal-content">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal">&times;</button>
								<h4 class="modal-title" style="text-align: center;">Profile Picture</h4>
							</div>
							<div class="modal-body">	
								<div class="form-group">
									<img 
									{% if selected_user_profile.user_photo_set.all %}
									{% for data in selected_user_profile.user_photo_set.all %}
									src="{{ data.profile_picture_link }}"
									{% endfor %}
									{%  else %}
									src="http://vignette1.wikia.nocookie.net/charmscrp/images/a/ac/Generic_Avatar.png/revision/latest?cb=20140819033443"
									{% endif %} 
									class="img-rounded" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19); width:100%; height:100%;" >
								</div>
							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
							</div>
						</div>
					</div>
				</div>
				<!-- End Pop up-->
			</div>
			
			<div class="clone-about-container" style="padding: 20px; width: 70%; float: right; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
				<h2>About</h2>
				
				{% if selected_user_profile.user_options_set.all %}
				{% for data in selected_user_profile.user_options_set.all %}
				<p>{{ data.about_bio }}</p>
				{% endfor %}
				{% else %}
				<p>
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vehicula scelerisque magna in commodo. Aenean in nibh ut mi dapibus suscipit. Donec quis porta eros. Etiam in hendrerit orci. Ut vel odio non nisi tincidunt maximus eu faucibus lorem. Aliquam congue sem est. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus consequat ligula eu lorem vulputate ornare. Proin in sem dolor. Mauris aliquet eleifend lacus, convallis sagittis nunc lacinia laoreet. Suspendisse varius efficitur augue. Aliquam mollis arcu at nulla vestibulum imperdiet. Vivamus porttitor purus sed dolor posuere, ac consequat urna mattis. Integer dictum sollicitudin ligula vel egestas. Pellentesque feugiat est velit, vitae fringilla arcu consequat nec. Nulla rhoncus metus vel magna pretium, id pharetra ipsum vehicula.
				</p>
				{% endif %}
				
				{% if selected_user_profile.user_options_set.all %}
				{% for data in selected_user_profile.user_options_set.all %}
				<h3>Location: {{ data.about_location }}</h3>
				{% endfor %}
				{% else %}
				<h3>Location: Cape Town</h3>
				{% endif %}

			</div>
			
			<hr style="clear: both;" />

			<!-- Posts -->
			{% if selected_user_profile.user_posts_set.all %}
				{% for data in selected_user_profile.user_posts_set.all %}
				<div style="margin-top: 20px; text-align:center; clear: both; padding: 30px; width: 100%;  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
					<p class="text-primary" style="font-weight: bold; text-align: left;"><em>On {{ data.pub_date }} - {{ selected_user_profile.user_name }} said:</em></p>
					<p>{{ data.post_made }}</p>
					<p style="width: 100%;">
						<form style="float: left; color: brown;" action="{% url 'facebook:like_post_other_profile' %}" method="POST"> 
								{% csrf_token %}
								<input style="display: none;" type="hidden" name="checkPostID" value="{{ data.id }}" />
								<button type="submit" class="" style="background-color: white; border: none;">Like <i class="glyphicon glyphicon-thumbs-up" style="vertical-align: middle;"></i></button><span style="margin-right: 5px; float: left; color: brown;"> {{ data.likes }}</span>
						</form>
					</p>
				</div>
				{% endfor %}
			{% else %}
			<div style="text-align:center; clear: both; padding: 30px; width: 100%;  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
				<p class="text-primary" style="font-weight: bold">News Feed</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vehicula scelerisque magna in commodo. Aenean in nibh ut mi dapibus suscipit. Donec quis porta eros.</p>
				<br />
			</div>
			{% endif %}
		</div>
		<div class="panel-footer panel-warning">
			<span class="glyphicon glyphicon-fire text-warning"></span>
		</div>
	</div>
</div>
</body>

</html>